name: project-ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  spec-check:
    uses: heybearc/sdd-foundation/.github/workflows/spec-check.yml@v1
  contracts:
    uses: heybearc/sdd-foundation/.github/workflows/contracts.yml@v1
  tests:
    uses: heybearc/sdd-foundation/.github/workflows/tests.yml@v1
  security:
    uses: heybearc/sdd-foundation/.github/workflows/security.yml@v1
  cost:
    uses: heybearc/sdd-foundation/.github/workflows/cost-report.yml@v1
  qos:
    uses: heybearc/sdd-foundation/.github/workflows/qos.yml@v1
    with:
      qos_url: ""            # optional: set your running endpoint URL
      p95_budget_ms: 200
      bundle_budget_kb: 200
  opa:
    uses: heybearc/sdd-foundation/.github/workflows/opa.yml@v1
  contracts-conformance:
    uses: heybearc/sdd-foundation/.github/workflows/contracts-conformance.yml@v1
    with:
      openapi_path: contracts/openapi.yaml   # change if different
      base_url: ""                           # set to your running API base URL to enable

# (Optional) Replace individual jobs with a single quality gate:
# quality:
#   uses: heybearc/sdd-foundation/.github/workflows/quality-gate.yml@v1
#   with:
#     qos_url: ""            # set when your API is running
#     p95_budget_ms: 200
#     bundle_budget_kb: 200
